.TH PYMYTHTVFS "8" "February 2013" "pymythtvfs - version 0.1" "System Administration Utilities"
.SH NAME
pymythtvfs \- manual page for pymythtvfs - version 0.1
.SH SYNOPSIS
.B pymythtvfs
[\fImountpoint\fR] [\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-o\fR opt,[opt...]
mount options
.TP
\fB\-\-version\fR
output version and exit
.PP
pymythtvfs \- version 0.1

