#!/usr/bin/env python
# pymythtvfs - Fuse based filesystem for MythTV
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import mythtvfs
import fuse
import sys

def safe_print(text):
    try:
        print text
    except:
        # Ignore any errors
        pass

def showLicense():
	safe_print("""pymythtvfs - version %s
THIS PROGRAM IS DISTRIBUTED UNDER THE GPL AND COMES WITH NO WARRANTIES
READ THE FILE COPYING AND README FOR MORE INFORMATION
""" % mythtvfs.VERSION)

if __name__ == "__main__":
    fs = mythtvfs.Fs()
    try:
        if fs.parse():
            showLicense()
            fs.connect()
            sys.stdout = open('/dev/null', 'w')
            sys.stderr = open('/dev/null', 'w')
            sys.stdin = open('/dev/null', 'r')
            fs.main()
            exit(0)
        elif fs.parser.print_version:
            safe_print("""pymythtvfs - version %s""" % mythtvfs.VERSION)
            exit(0)
    except mythtvfs.MissingOptionException as e:
        safe_print("Missing option: " + e.missing)
        safe_print()
        fs.parser.print_help()
        exit(1)
    except fuse.FuseError as e:
        safe_print("Error: " + e.message)
        exit(2)
