#!/usr/bin/env python
# pymythtvfs - Fuse based filesystem for MythTV
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import mythtvfs
import fuse
import sys
import logging

def showLicense(print_fn = None):
    text = ("""pymythtvfs - version %s
THIS PROGRAM IS DISTRIBUTED UNDER THE GPL AND COMES WITH NO WARRANTIES
READ THE FILE COPYING AND README FOR MORE INFORMATION
""" % mythtvfs.VERSION)
    if print_fn:
        print_fn(text)
    else:
        print text

if __name__ == "__main__":
    fs = mythtvfs.Fs()
    try:
        showLicense()
        if fs.parse():
            fs.connect()
            # Make sure the license ends in the log
            showLicense(logging.info)
            fs.main()
            exit(0)
        elif fs.parser.print_version:
            exit(0)
    except mythtvfs.MissingOptionException as e:
        print "Missing option: " + e.missing
        print
        fs.parser.print_help()
        exit(1)
    except fuse.FuseError as e:
        print "Error: " + e.message
        exit(2)
